### ISSUE TITLE
pnpm run dev failed

### ISSUE THREAD

**Issue by chengfengfengwang** [linchen1987/ai-summarizer#1]
1. pnpm i
2. pnpm run dev, get error: 
```
🔴 ERROR  | Failed to resolve './gen-assets/icon16.plasmo.png' from './.plasmo/chrome-mv3.plasmo.manifest.json'
🔴 ERROR  | Cannot load file './gen-assets/icon16.plasmo.png' in './.plasmo'.
```
<img width="749" alt="image" src="https://github.com/linchen1987/ai-summarizer/assets/23279667/5c2d2ee9-1d4b-4072-b9f7-ecac4ca3d182">

**Comment by linchen1987** [comment]
fixed https://github.com/linchen1987/ai-summarizer/commit/9053c8b28ca718e8dbf48bdea2b78367cfa90b0f
